apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc/
  - loki.yaml
  - promtail.yaml
  - grafana.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml