apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:

      # =========================
      # PROMETHEUS SELF METRICS
      # =========================
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      # =========================
      # NODE EXPORTER (CPU/RAM/DISK)
      # =========================
      - job_name: "node-exporter"
        kubernetes_sd_configs:
          - role: pod

        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            action: keep
            regex: prometheus-node-exporter

      # =========================
      # KUBE STATE METRICS (K8s objects)
      # =========================
      - job_name: "kube-state-metrics"
        kubernetes_sd_configs:
          - role: pod

        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            action: keep
            regex: kube-state-metrics

      # =========================
      # APPLICATION PODS (ONLY ANNOTATED)
      # =========================
      - job_name: "kubernetes-pods"
        kubernetes_sd_configs:
          - role: pod

        relabel_configs:

          # ONLY scrape pods with annotation
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: "true"

          # FIX: proper port mapping (NO 9100:80 BUG)
          - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: (.+);(.+)
            replacement: $1:$2
            target_label: __address__
