apiVersion: v1
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods

        kubernetes_sd_configs:
          - role: pod

        pipeline_stages:
          - cri: {}

        relabel_configs:

          - source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace

          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod

          - source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container

          - source_labels:
              - __meta_kubernetes_pod_label_app
            target_label: app

          - replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"promtail.yaml":"server:\n  http_listen_port: 9080\n\npositions:\n  filename: /tmp/positions.yaml\n\nclients:\n  - url: http://loki:3100/loki/api/v1/push\n\nscrape_configs:\n  - job_name: kubernetes-pods\n\n    kubernetes_sd_configs:\n      - role: pod\n\n    pipeline_stages:\n      - cri: {}\n\n    relabel_configs:\n\n      - source_labels:\n          - __meta_kubernetes_namespace\n        target_label: namespace\n\n      - source_labels:\n          - __meta_kubernetes_pod_name\n        target_label: pod\n\n      - source_labels:\n          - __meta_kubernetes_pod_container_name\n        target_label: container\n\n      - source_labels:\n          - __meta_kubernetes_pod_label_app\n        target_label: app\n\n      - replacement: /var/log/pods/*$1/*.log\n        separator: /\n        source_labels:\n          - __meta_kubernetes_pod_uid\n          - __meta_kubernetes_pod_container_name\n        target_label: __path__\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"promtail-config","namespace":"monitoring"}}
  creationTimestamp: "2026-04-19T04:34:16Z"
  name: promtail-config
  namespace: monitoring
  resourceVersion: "184272"
  uid: 74d52d35-c147-4155-9ea3-4e6045b9d06d
