apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-envd
  namespace: app
data:
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: https://nixie.my.id

  DB_HOST: mysql
  DB_PORT: "3306"

  CACHE_DRIVER: redis
  QUEUE_CONNECTION: redis
  SESSION_DRIVER: redis
  REDIS_HOST: redis