apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: infra
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ppdbnu
  MYSQL_DATABASE: ppdb-smp
  MYSQL_USER: root
  MYSQL_PASSWORD: ppdbnu