apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx
        image: zauzj/nginx-ppdb:v1.0.12

        volumeMounts:
        - name: uploads
          mountPath: /var/www/storage/app/public
          
        - name: public-build
          mountPath: /var/www/public

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

        securityContext:
          allowPrivilegeEscalation: false

        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3

      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: laravel-storage-pvc
            
        - name: public-build
          persistentVolumeClaim:
            claimName: laravel-public-pvc
